
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/bookyourservice-repo/$_SERVICE_NAME:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/bookyourservice-repo/$_SERVICE_NAME:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/bookyourservice-repo/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/bookyourservice-repo/$_SERVICE_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'bookyourservice'
  _DEPLOY_REGION: 'europe-west1'
